### ISSUE TITLE
Published datasets aren't showing up on datasets page, same for published blog entries under data stories

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/sldata#6]
There are only 5 listed here: http://live.data.sierraleone.nucivic.build/dataset

The 6th ought to be this one, the voter registration dataset: http://live.data.sierraleone.nucivic.build/group/demographics

It's up, it's published - where did it go?

**Comment by stefaniefgray** [comment]
Update: This is still happening with every single dataset I've uploaded -- and it's also happening with data stories.

There are 4 data stories published and visible on the front page, but in the list of data stories, only 1 is visible: http://live.data.sierraleone.nucivic.build/stories

**Comment by grantdobbe** [comment]
Is this still happening on production?

**Comment by jvitello** [comment]
Grant thinks this is an indexing issue, possibly due to a missing table in the db

**Comment by grantdobbe** [comment]
Solution on dev with dkan-1.7 codebase:
```
drush features-revert --force -y dkan_sitewide_search_db # this forces the recreation of tables
drush sapi-r # this queues all indexes for rebuild
drush cron # this actually makes the reindexing happen
```
http://dev.data.sierraleone.nucivic.build/stories
http://dev.data.sierraleone.nucivic.build/dataset

**Comment by grantdobbe** [comment]
Ok, issue appears to be resolved on production. Please verify.

http://live.data.sierraleone.nucivic.build/stories
http://live.data.sierraleone.nucivic.build/dataset

**Comment by stefaniefgray** [comment]
Fixed for blog entries under data stories

**Comment by jvitello** [comment]
Data stories are FIXED and all are displaying in the list

There are still some issues with the dataset listings:

The groups page lists all of the 14 datasets correctly...
http://live.data.sierraleone.nucivic.build/groups
![dataset_all_groups](https://cloud.githubusercontent.com/assets/5174815/6857555/ddfbc5be-d3dd-11e4-8633-7e212265b0dc.png)

... but the dataset list only shows 8.
http://live.data.sierraleone.nucivic.build/dataset
![datasets_all_list](https://cloud.githubusercontent.com/assets/5174815/6857730/4785e824-d3df-11e4-9acb-04f4f04229cf.png)


Similarly, if you look at a single blog group...
http://live.data.sierraleone.nucivic.build/groups
![dataset_group](https://cloud.githubusercontent.com/assets/5174815/6857864/310a7438-d3e0-11e4-977e-e1bfc1927027.png)

... the list view of the blog group doesn't show all of the entries.
http://live.data.sierraleone.nucivic.build/group/demographics
![dataset_group_list](https://cloud.githubusercontent.com/assets/5174815/6857890/695364c6-d3e0-11e4-9abd-7bb218dba138.png)


Stefanie still thinks this is related to time, and when she posted the datasets. All newly created datasets are showing up correctly.

**Comment by jvitello** [comment]
Stefanie added more datasets last night, so the numbers in my images aren't accurate. But the bug still persists.
